---
# tasks file for ansible-role-vif

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"


- name: Create virtual interface file
  template:
    src: hostname.if.j2
    dest: "/etc/hostname.{{ item['name'] }}"
    owner: root
    group: wheel
    mode: "0600"
    validate: sh -n %s
  register: __vif_create_virtual_interface_file
  with_items: "{{ vif_config | sort(attribute='priority', reverse = True) }}"

- name: Create virtual interfaces
  ansible.builtin.command: "sh /etc/netstart {{ item['item']['name'] | quote }}"
  with_items: "{{ __vif_create_virtual_interface_file['results'] }}"
  when:
    - item['changed']
