---
# tasks file for ansible-role-vif

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ vif_log_dir }}"
    mode: 0755
    owner: "{{ vif_user }}"
    group: "{{ vif_group }}"
    state: directory
  notify: Restart vif

- name: Create db directory
  file:
    path: "{{ vif_db_dir }}"
    mode: 0755
    owner: "{{ vif_user }}"
    group: "{{ vif_group }}"
    state: directory
  notify: Restart vif

- name: Create vif.conf
  template:
    src: vif.conf.j2
    dest: "{{ vif_conf_file }}"
    validate: echo %s
  notify: Restart vif

- name: Start vif
  service:
    name: "{{ vif_service }}"
    enabled: true
    state: started
